---
- name: Foobar
  hosts: all
  become: true
  tasks:
    - name: Create foo group
      ansible.builtin.user:
        name: foo
        state: present
    - name: Create foo user
      ansible.builtin.user:
        name: foo
        uid: 1001
        group: foo
    - name: Create a file
      ansible.builtin.file:
        state: touch
        path: /etc/foo.conf
        owner: foo
        group: foo
        mode: '0644'
